<a href="https://colab.research.google.com/github/dprobity/pytorch/blob/main/pytorch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
# we do matrix, gradient computations using tensors


import torch
import torch.nn as nn


a  = torch.ones(5,6)

print(a)

sum = torch.sum(a, 1)

sum



[x,y] = a.size()

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [2]:
import numpy as np

# Creating a 2D array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)

print(arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [17]:
import torch

from math import sqrt
import numpy as np

a = torch.tensor([[
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9],
     [10, 11, 12]]
]])


print(a)


print(a.shape)


squeezed = torch.squeeze(a)

print(squeezed)
print(squeezed.shape)

unsqqueezed = torch.unsqueeze(squeezed, dim=1)

print(unsqqueezed)
print(unsqqueezed.shape)

tensor([[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9],
          [10, 11, 12]]]])
torch.Size([1, 1, 4, 3])
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
torch.Size([4, 3])
tensor([[[ 1,  2,  3]],

        [[ 4,  5,  6]],

        [[ 7,  8,  9]],

        [[10, 11, 12]]])
torch.Size([4, 1, 3])


In [21]:
## Neural nets

# Constructor

# Forward -> get_model_prediction(example_datapoint)

import torch.nn as nn
import torch.nn.functional as F

class MyModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.first_layer = nn.Linear(in_features=4, out_features=6)
    self.second_layer = nn.Linear(in_features=6, out_features=6)
    self.thrid_layer = nn.Linear(in_features=6, out_features=2)

  def forward(self, x):
    first_layer_output = self.first_layer(x)
    second_layer_output = self.second_layer(first_layer_output)
    thrid_layer_output = self.thrid_layer(second_layer_output)
    return thrid_layer_output

    # we can return then chain of computations as a oneliner to make it more concise --->>> self.third_layer(self.second_layer(self.first_layer(x)))


model = MyModel()

example_datapoint = torch.rand(1,4)


print(model(example_datapoint))












tensor([[ 0.1177, -0.3896]], grad_fn=<AddmmBackward0>)


In [11]:
import torch

import torch.nn as nn


a = torch.arange(0, 5)

print(a)


b= torch.arange(4.)

print(b)

tensor([0, 1, 2, 3, 4])
tensor([0., 1., 2., 3.])


In [13]:
import torch
# Original tensor with a singleton dimension
x = torch.tensor([[[1, 2, 3, 4]]]) # Shape: (1, 1, 4)
# Using torch.squeeze to remove singleton dimensions
squeezed = x.squeeze() # Shape: (4,)
# Using torch.reshape to achieve the same result
reshaped = x.reshape(4) # Shape: (4,)
print("Original shape:", x.shape)
print("After squeeze:", squeezed.shape)
print("After reshape:", reshaped.shape)


Original shape: torch.Size([1, 1, 4])
After squeeze: torch.Size([4])
After reshape: torch.Size([4])
